### ISSUE TITLE
🪲 Bug Report - typo on line 1337 of the '3_wara_reports_generator.ps1' script

### ISSUE THREAD

**Issue by tcorveleyn** [Azure/Azure-Proactive-Resiliency-Library-v2#115]
## Describe the bug

Typo on line 1337 of the '3_wara_reports_generator.ps1' script > starts with 'Sif' instead of 'If'

## To Reproduce

Steps to reproduce the behaviour: none

## Expected behaviour

Line 1337 should be an if-statement, but it starts with 'Sif'. Guessing this is a typo.

**Comment by Claudio-Merola** [comment]
Fixed on version 2.0.9
