### ISSUE TITLE
❓👂 Question/Feedback - Colorblind people cannot see the anchor icon, try different color combination in the dark theme

### ISSUE THREAD

**Issue by rodrigosantosms** [Azure/Azure-Proactive-Resiliency-Library-v2#120]
## Question/Feedback

Colorblind people cannot easily see the anchor icon, try different color combination in the dark theme.

## Possible Answers/Solutions?

Change cell background color or change icon color.

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/20050577/0ba082cc-f840-4e57-bf75-846ae1407dd1)

**Comment by oZakari** [comment]
Hi @rodrigosantosms, does this look better? 
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/30884663/27dc4238-9614-4e4d-bd75-4e3e593525f6)
