### ISSUE TITLE
Bug: Incorrect Guidance on the Action Plan Spreadsheet Analysis

### ISSUE THREAD

**Issue by jeetgarg** [Azure/Azure-Proactive-Resiliency-Library-v2#126]
## Describe the bug
I am conducting a WARA for a CX and ran the collector script using Cloud Shell due to certain limitations of the cxs environment.
Using the Data Analyzer script, the Action Plan spreadsheet was generated.
Now, as per the guidance, under " Local Machine - Action Plan Analysis" - 2nd point:
    _Go to the “ImpactedResources” worksheet, filter Column “B” by “IMPORTANT”, and validate manually the remaining resource configurations for reliabilty patterns.
    
        “IMPORTANT - Query under development”
        “IMPORTANT - Recommendation cannot be validated with ARGs - Validate Resources manually”
        “IMPORTANT - ServiceType Not Available in APRL - Validate Resources manually if Applicable, if not delete this line”__
When I follow the guidance, I cant find:
“IMPORTANT - Query under development”
        “IMPORTANT - Recommendation cannot be validated with ARGs - Validate Resources manually”
I tried filtering all the columns not just "Cloumn B".

Also,  “IMPORTANT - ServiceType Not Available in APRL - Validate Resources manually if Applicable, if not delete this line” is under Column A not B.

## To Reproduce

Steps to reproduce the behaviour:

You can run the script and find similar behavior. In case of any challenges, please feel free to loop me in to demonstrate.

## Screenshots 📷

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/47571120/f9cdc768-fe3a-4de8-9c4c-ba2504c90d4c)
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/47571120/38e379be-ca9e-4262-a136-fa317268e321)

**Comment by jeetgarg** [comment]
Any update on this issue?
I have received no response, and this is impacting my ongoing assessment.

**Comment by Claudio-Merola** [comment]
Hey @jeetgarg 

Can you confirm this still occurs on version 2.0.9?

**Comment by kpoineal** [comment]
Closing this due to no response. Please reach out internally if this is still ongoing and we will address.
