### ISSUE TITLE
Bug : Multiple rows of the same Resource Types in the Action Plan - ResourceTypes worksheet

### ISSUE THREAD

**Issue by jeetgarg** [Azure/Azure-Proactive-Resiliency-Library-v2#127]
In the Action Plan spreadsheet, under ResourceTypes worksheet, I see multiple rows of the same resource types from the same subscription. This is confusing to interpret and explain to the customer.

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/47571120/e632d2b9-5273-4ec7-8baa-55f54d97fc00)
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/47571120/1abb06ed-82f1-4964-8a41-578833c03678)

**Comment by Claudio-Merola** [comment]
@jeetgarg 

Did you use the -ResourceGroup filtering?

**Comment by jeetgarg** [comment]
@Claudio-Merola Yes!

**Comment by Claudio-Merola** [comment]
Hey @jeetgarg 

This should also be already fixed, can you confirm that too?
