### ISSUE TITLE
Bug: Issues with the Recommendations Worksheet in the Action Plan Spreadsheet

### ISSUE THREAD

**Issue by jeetgarg** [Azure/Azure-Proactive-Resiliency-Library-v2#128]
If i filter out Implemented column to - yes, it shows number of impacted resources as 0. 
Now, if you check for recommendations where there is a query, and number of impacted resources are 0, this is fine. but it shows the same for queries under development too.

This is where the query is developed and it shows zero impacted resources which is alright.
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/47571120/87dac8a5-3f63-4a21-bdd9-e0760059e713)

This is where there is no query and it still shows Implemented as Yes and Number of Impacted resources 0:

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/47571120/77d561e7-fd6f-42e2-974b-46392c8cf49d)

**Comment by Claudio-Merola** [comment]
@jeetgarg 

Can you validate if this still occurs with the collector script version 2.0.9?

I believe this would happen with the older versions, but now there should not be any "Query under development" without any impacted resource.

**Comment by jeetgarg** [comment]
@Claudio-Merola I ran the script on Tuesday 14th May and used the latest available script. Has the script changed post that? If yes, then I can ask the cx to run it again.

**Comment by jeetgarg** [comment]
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/47571120/8b1a3e9a-6374-4513-b448-60c9a2573fe6)
This snap is from the sample output here: https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main/tools/sample-output and it shows the same thing that it shows no impacted resources as 0 and implemented as yes for a recommendation which has no query.

**Comment by jeetgarg** [comment]
Hey @Claudio-Merola, any update on this?

**Comment by Claudio-Merola** [comment]
Hello there @jeetgarg 

I have submitted a Pull Request that should address this and the other bug you posted regarding Resource Types. But it was not merged yet.

Since you are in the middle of an assessment. You could use the updated version of the "1_wara_collector.ps1" and "2_wara_data_analyzer.ps1" from my forked repo. That version should work.

**Comment by oZakari** [comment]
Hi @Claudio-Merola, in the related PR form, could you please add the following: `Fixes #128` so it will automatically close this issue when it is merged.

**Comment by Claudio-Merola** [comment]
Hi @oZakari 

I usually do, but in this case I prefer to validate it before assume the PR will fix this

**Comment by jeetgarg** [comment]
Hey @Claudio-Merola 
Is this done?

**Comment by Claudio-Merola** [comment]
Hey @jeetgarg 

Yes, this issue should be already fixed on version 2.0.9. 

Can you validate it?

**Comment by kpoineal** [comment]
@jeetgarg Closing this issue. If you still have problems please re-open or create a new issue. Thank you!

**Comment by jeetgarg** [comment]
[like]  Jeet Garg reacted to your message:
________________________________
