### ISSUE TITLE
❓👂 Question/Feedback - recommendations.yaml' because it does not exist.

### ISSUE THREAD

**Issue by chiuhoms** [Azure/Azure-Proactive-Resiliency-Library-v2#142]
while I am running the script, the error showing as below: ("WAFworking" is my temp folder)

Get-Content : Cannot find path 'C:\WAFworking\recommendations.yaml' because it does not exist.
At C:\WAFworking\2_wara_data_analyzer.ps1:127 char:44
+ ...        $Global:ServicesYAMLContent += Get-Content -Path $YAML | Conve ...
+                                           ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\WAFworking\recommendations.yaml:String) [Get-Content], ItemNotFoundE
   xception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

I can see that the git is running smooth, and related information of recommendation is in the folder. Not sure why this is happening.

**Comment by oZakari** [comment]
Hi @chiuhoms, could you please check which version of the data analyzer script you're using and ensure it is the latest (2.0.9)?
