### ISSUE TITLE
🪲 Bug Report - "Collector": "2.0.10" - Authentication fails if DefaultSubscriptionForLogin is different from a specified one as parameter of the script

### ISSUE THREAD

**Issue by nekdima** [Azure/Azure-Proactive-Resiliency-Library-v2#148]
## Bug scope
Script name: 1_wara_collector.ps1
Script version: 2.0.10

## Describe the bug Nr.1
Authentication fails if DefaultSubscriptionForLogin is different from the specified to as parameter of the script.

## To Reproduce
Authenticate against a different tenant or subscription. Close the PowerShell session. Then, open a new PowerShell session and attempt to authenticate using the script parameters for the desired target subscription and tenant. The authentication should fail.

## Expected behaviour

Smooth authentication experience regardless of previous authentication history.

## Bug Nr.2
Interactive menu pop-up despite providing subID and tenantID.

## Screenshots 📷
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/38444705/e71c1549-3fb6-4b20-ac25-c885779cf3e8)

## Proposed Fix for bug Nr.1

Add cmdlet "Clear-AzConfig -DefaultSubscriptionForLogin" to **function Connect-ToAzure**

**Comment by ejhenry** [comment]
@Azure/aprl-wara-tools please review

**Comment by kpoineal** [comment]
@nekdima Is this still occurring with the latest release of the script? Please let me know!

**Comment by nekdima** [comment]
> @nekdima Is this still occurring with the latest release of the script? Please let me know!

@kpoineal Yes, the issue is still present. 

1. Authentication on macOS or Linux is not possible unless using CloudShell (Mariner Linux + managed identity).
2. Users are prompted unnecessarily for input with the new interactive login experience (starting from Az 12.0.0) even after providing the required information inline or through the config file.

I will try again and submit a PR to address this issue. :)
