### ISSUE TITLE
Question/Feedback: Ensure both connections of an ExpressRoute circuit are configured in active-active mode - How does this query check if you are forcing active\passive via advertising more specific routes and BGP AS path prepending?

### ISSUE THREAD

**Issue by judyer28** [Azure/Azure-Proactive-Resiliency-Library-v2#16]
## Question/Feedback

I am not sure if the query, [Ensure both connections of an ExpressRoute circuit are configured in active-active mode](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/expressRouteCircuits/#ensure-both-connections-of-an-expressroute-circuit-are-configured-in-active-active-mode) query is working as expected.  The query is checking if the primary and secondary peerings have address prefixes like so:
| where not(properties.peerings[0].properties.primaryPeerAddressPrefix != "null" and  properties.peerings[0].properties.secondaryPeerAddressPrefix != "null")

But if I was doing the following as described in the [docs](https://learn.microsoft.com/en-us/azure/expressroute/designing-for-high-availability-with-expressroute#active-active-connections), would this condition catch that?

"However, through your route advertisements, you can force the redundant connections of an ExpressRoute circuit to operate in active-passive mode. Advertising more specific routes and BGP AS path prepending are the common techniques used to make one path prefer over the other."

Looking for confirmation from an ExpressRoute\Networking SME before creating a bug report.  Thanks.

**Comment by ehaslett** [comment]
I believe there are 2 interpretations of active here. One is "is the connection itself configured and enabled", the other is "is one link passive in the sense that routing techniques direct traffc to the other connection". The intent of this original was to address the first, but not the second. The ARG query does not seem to be working to address even the first. I suggest we determine what we are trying to accomplish with this recommendation. I would think both are important. The second one interpretation is more difficult to write an ARG query for. @judyer28 - what are your thoughts?

**Comment by ejhenry** [comment]
If the ARG query is not returning accurate results, it should be removed from the recommendation.

**Comment by ejhenry** [comment]
cc @JefferyMitchell

**Comment by JefferyMitchell** [comment]
@fguerri Would you review the points the team has made here and provide your thoughts. I did not think we were completed with sign off that recommendation ID's in ARG would be the path forward. Feature 34450 in Reliability backlog.

**Comment by JefferyMitchell** [comment]
@cshea-msft Could you help us with team member who created the ARG Query?

**Comment by cshea-msft** [comment]
@JefferyMitchell reached out to the PG contact, she mentioned she did not create the query but "Instead today there's no way to query using ARG to get Active Active\Active Passive" she is working on a Kusto equivalent for Advisor but security issues have taken precedence. Hope this helps.
