### ISSUE TITLE
🪲 Bug Report - The collector script fails when executed in the Cloud Shell

### ISSUE THREAD

**Issue by rseso** [Azure/Azure-Proactive-Resiliency-Library-v2#167]
## Describe the bug

The WARA collector script fails to run when executed from the Cloud Shell, but does work when executed from a local PowerShell session.

## To Reproduce

Steps to reproduce the behaviour:

1. Execute the collector script following the instructions at https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/tools/script-overviews/#11---cloud-shell
2. The script will log out from the current session but will fail to sign in again, throwing multiple error messages when attempting to run the remaining commands. The resulting JSON file will be created, but will have no meaningful content.

## Expected behaviour

The script should be able to execute without exceptions from the Cloud Shell.

## Screenshots 📷

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/10517981/398f5a2f-d83f-4580-add9-9b3bc222f2d5)

## Additional context

The bug seems to be in the function `Connect-ToAzure` on the line 211 (version 2.0.10) where we check whether we are in the Cloud Shell by querying the `$Script:CShell` property which, however, was never set in the script:
`if (!$Script:CShell)`

The $Script:CShell should be set to `$true` if we are in the Cloud Shell and to `$false` if we are running locally at the start of the script (for example on the line 32, right after `$Script:ShellPlatform = $PSVersionTable.Platform`.

There are two ways to check whether the script is executing in the Cloud Shell:

1.  `$env:AZUREPS_HOST_ENVIRONMENT` returns "cloud-shell/1.0" in the Cloud Shell, does not exist when executed locally, so something like this should work:

`$Script:CShell = Test-Path env:AZUREPS_HOST_ENVIRONMENT`

2. `Get-CloudDrive` cmdlet -> works on Cloud Shell, throws an exception locally, so we can use something like this:

`try {Get-CloudDrive | Out-Null; $Script:CShell=$true} catch {$Script:CShell=$false} `

**Comment by Claudio-Merola** [comment]
Fixed with Collector version 2.0.11
