### ISSUE TITLE
🪲 Bug Report - The collector script throws when executed on a system without Azure CLI installed

### ISSUE THREAD

**Issue by rseso** [Azure/Azure-Proactive-Resiliency-Library-v2#168]
## Describe the bug

The collector script version 2.0.10 calls the Azure CLI on the line `213 az account clear | Out-Null` which is not necessary since the PowerShell equivalent of this command is already in place on the next line `214 Clear-AzContext ...`. In addition, the script will throw an exception when it reaches the line 213 if executed on a system where Azure CLI is not installed.

## To Reproduce

Steps to reproduce the behaviour:

1. Execute the collector script version 2.0.10 on a system without Azure CLI installed. It will throw an exception on the line 213

## Expected behaviour

The script should have no dependency on Azure CLI and should be able to execute on a system without Azure CLI being installed on it.

## Screenshots 📷

N/A

## Additional context

The bug can be fixed by either deleting or commenting out the line 213 in the version 2.0.10 of the collector script:

`213 az account clear | Out-Null`

**Comment by Claudio-Merola** [comment]
Hello @rseso 

I believe this was already fixed, can you check if this still occurs with version 2.0.11?

**Comment by rseso** [comment]
> Hello @rseso
> 
> I believe this was already fixed, can you check if this still occurs with version 2.0.11?

Yes, it seems to be fixed in 2.0.11, together with the #167
