### ISSUE TITLE
🪲 Bug Report - Enable zone redundancy for Event Hub namespace - There is no API available for customer to update existing AZ

### ISSUE THREAD

**Issue by cbezenco** [Azure/Azure-Proactive-Resiliency-Library-v2#17]
## Describe the bug

Customer has been looking for ways to enable AZ on existing Event Hub namespace. After clarification with PG, there is no way for customer to update this setting. Clarification from PG (Christina Compy) shared below:

There is no API for a customer to enable AZ on a namespace as stated [here](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/EventHub/namespaces/#enable-zone-redundancy-for-event-hub-namespace).  We are in the process of migrating all infrastructure to AZ in regions that support it and as the AZ capacity is built out.  Much has already been done as a matter of fact.  As we do this migration that adds AZ support. You see no change in your bill. You don’t have to do a migration.  You just get AZ support.  

The exception to this is Event Hubs dedicated.  With Event Hubs dedicated we can’t yet offer AZ support for 1CU and 2CU clusters.  We can enable it for 3CU and above but for now that is just via a support request.  We are planning on making this better as we get some capabilities to do so.  

For now though, the important thing to note is that customers don’t have an API/UI to enable AZ, but will just get it automatically except for Event Hubs dedicated and several regions (for a little while) as the AZs are built out._  

## To Reproduce

NA

## Expected behaviour

It might still make sense to raise awarness that Eventhub Namespace are not yet enabled but the recommendation should make it clear that Microsoft engineering is in the process of upgrading the AZ infrastructure.

## Additional context

Anything else we should know to help us troubleshoot this bug? Follow-up with Christina Compy for more details/confirmation.

**Comment by oZakari** [comment]
Hey @cbezenco, thanks for calling this out and apologies for the delayed response. Apologies as I am not an expert for Event Hub, but I am a little confused on the [associated docs](https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-geo-dr?tabs=portal#availability-zones) stating that there is the ability configure namespaces within availability zones and to disable it through PowerShell or CLI.

**Comment by cbezenco** [comment]
Sorry I was OOF for the last 2 weeks for Easter Break.

@oZakari, I cannot comment on the doc you shared. I am forwarding you message from EventHub PG, may be you can use it to ask for clarification on the doc ?

**Comment by oZakari** [comment]
@cbezenco, currently hiding this recommendation until the infrastructure is migrated for all namespaces. Have also adjusted the wording to be aligned to what was stated from PG. 

Will keep this open until I can confirm with PG that the migration is complete. Thanks again for calling this out!
