### ISSUE TITLE
🪲 Bug Report - 1_wara_collector.ps1 -  Failing authentication on non-Windows devices - scripts expects MSI - bug fix is inside

### ISSUE THREAD

**Issue by nekdima** [Azure/Azure-Proactive-Resiliency-Library-v2#176]
## Describe the bug

File: 1_wara_collector.ps1

Failing authentication on non-Windows devices. The script scripts expects MSI on the line 246 due to the use of -Identity parameter. 

## To Reproduce

Run the script on non-Windows device
## Bug fix

Remove **-Identity** parameter on the line 246.

Optional: Add Write-Output to provide output to the console.

**Comment by ejhenry** [comment]
@Azure/aprl-wara-tools please review
