### ISSUE TITLE
💡 Feature Request - Missing APRL checks for RSV

### ISSUE THREAD

**Issue by sforstre** [Azure/Azure-Proactive-Resiliency-Library-v2#18]
## Describe the solution you'd like

There are today no checks for recovery service vaults included in APRL and should be checked in WARA as they play in IaaS based environments often a critical role in BCD**R**

## Describe alternatives you've considered

I'm covering today the part manually (check if ZRS or GRS, check if MUA or immutability is setup..)

**Comment by ejhenry** [comment]
@sforstre the RSV recommendations can be found here - https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/RecoveryServices/vaults/

Can you list the additional recommendations that should be added?
