### ISSUE TITLE
🪲 Bug Report - Shared disks query lists disk with no shared disk enabled

### ISSUE THREAD

**Issue by ems75** [Azure/Azure-Proactive-Resiliency-Library-v2#183]
## Describe the bug

The query id 3263a64a-c256-de48-9818-afd3cbc55c2a (Shared disks should only be enabled in clustered servers) is listing disks which don't have shared disks enabled.
The query is looking for disks where their property "maxShares" is not null.
However, after doing some tests, it looks like that the PV2 disks have the property maxShares=1 by default even if the shared disk feature is not enabled.

## To Reproduce

Steps to reproduce the behaviour:

1. Run the query against a PV2 disk
2. Run the query against a non PV2 disk 
3. Compare

## Expected behaviour

A clear and concise description of what you expected to happen without this bug 🙂

## Screenshots 📷

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/63883633/35057d4b-fa05-4aee-ad25-3074e70e37ce)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/63883633/71c463cc-b6d4-43e3-b9cf-f624d1e308ce)

## Additional context

Anything else we should know to help us troubleshoot this bug?

**Comment by ejhenry** [comment]
cc @pinyuko

**Comment by pinyuko** [comment]
@ejhenry , maybe we should remove this ARG?

**Comment by ejhenry** [comment]
> @ejhenry , maybe we should remove this ARG?

Thanks @pinyuko. I agree, we should remove the ARG until we have one that doesn't return false positives.

**Comment by ejhenry** [comment]
@tksh164 can you check if there is an update we can make to the query to catch this issue?

**Comment by tksh164** [comment]
@ejhenry I will check it

**Comment by tksh164** [comment]
This issue has already been fixed by the following PR #182.

The code change:
https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pull/182/files#diff-576162e32186c4ec7a4c512016406906f859c2b25f8d53a0cb55ee36099262be

The current query filtering wtih `properties.maxShares >= 2`.

https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/1c66931c4bcbef8e5e161e1ff566f9f8dd66c74c/azure-resources/Compute/virtualMachines/kql/3263a64a-c256-de48-9818-afd3cbc55c2a.kql#L5

**Comment by tksh164** [comment]
Hi @ems75, could you try with the latest APRL query?

**Comment by oZakari** [comment]
Closing as referenced by @tksh164's pr. @ems75 please feel free to re-open if the come across the same issue in the future.
