### ISSUE TITLE
🪲 Bug Report -  Query for recommendation 'Configure configure resource health alerts' missing

### ISSUE THREAD

**Issue by ReneHezser** [Azure/Azure-Proactive-Resiliency-Library-v2#19]
## Describe the bug

The query for [Configure configure resource health alerts is missing](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Insights/activityLogAlerts/#configure-resource-health-alerts). 

## Additional context

**Comment by oZakari** [comment]
Closing as the recommendation cannot be validated with ARG at this time.
