### ISSUE TITLE
💡 Feature Request - Add Azure App Configuration to Azure Resource recommendations

### ISSUE THREAD

**Issue by bolt-io** [Azure/Azure-Proactive-Resiliency-Library-v2#191]
## Describe the solution you'd like

[Azure Resources](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/) does not cover [Azure App Configuration](https://aka.ms/appconfig) recommendations.

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by ejhenry** [comment]
#190 contains two new recommendations for App Configuration

**Comment by oZakari** [comment]
Closing as ejhenry referenced existing recommendations. @bolt-io if you have other recommendations that you believe should be added, please consider creating a PR or creating an issue with the specific recommendations you think should be added. Thank you!
