### ISSUE TITLE
💡 Feature Request - Suggest we add Load Balancer Health Probe guidance to APRL

### ISSUE THREAD

**Issue by stevedistef** [Azure/Azure-Proactive-Resiliency-Library-v2#20]
## Describe the solution you'd like

In an analysis of recent Azure outage, I found that the azure load balancer used to feed traffic to a pair of Active Standby NVA firewalls were set to probe TCP Port 22 on the VMs.  So, when the active NVA got into a "memory conserve mode" (because of firewall application issues) the Firewall was no longer working, but you could continue to establish TCP connectivity to the Azure VM hosting it, so it was never declared DOWN by the Azure Load Balancer, thus the failover never triggered.   Since all East-West traffic was routed through this pair of NVA FWs with UDRs, this causes a complete outage.    It had occurred in 3 different deployments and so we are sure this was the root cause. In all cases the passive Firewall could have taken over avoiding the outage duration.

## Describe alternatives you've considered
The APRL has a section for Load Balancer reliability recommendations and so I believe we should recommend that customers refer to their firewall vendor documentation to determine what ports and protocols should be used to determine the heath of the firewall application and use that for the Azure LB Health Probe.

I found this of Fortinet pages as an example.
[Technical Tip: FortiGate-VM probe on Azure load ba... - Fortinet Community](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcommunity.fortinet.com%2Ft5%2FFortiGate%2FTechnical-Tip-FortiGate-VM-probe-on-Azure-load-balancer%2Fta-p%2F250184&data=05%7C02%7Cstdistef%40microsoft.com%7Cfb7c9fbf23854af7c3da08dc2da2856f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638435423268748554%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=A042AyJUbEutI6Gql7TFflLu5SeYIoirk5GKwSKKQhI%3D&reserved=0)

I am not suggesting we need to be prescriptive for each vendor, but some verbiage to warn that a VM will respond to TCP port 22 in cases where the FW App is stuck…..

## Additional context

Add any other context or screenshots about the feature request here. 📷
When the backend pool is a pair of active standby NVAs, we should add a LB-5 that encourages the customer to implement health probes which probe the NVA applications itself (PAN, FortiGate, Cisco…etc.).  Not just TCP port 22 like many customers do:
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/159309739/d5f07e6d-93da-4e44-98c3-7b106f08bede)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/159309739/1334c2fb-5e77-4d8a-94e4-6164eccb2acd)

**Comment by jimays-avila** [comment]
@ehaslett I see your point on this.  Should we discuss this further to see if it should move forward or be removed? Happy to discuss this with you and other Networking SMEs.  We could create a recommendation around using custom health probes instead of the default that sends the request to the loopback adapter and we can add a reference to what has been stated above.

**Comment by ehaslett** [comment]
@JefferyMitchell / @wamota  - can this get added to review in our weekly meeting and/or create a user story?

**Comment by JefferyMitchell** [comment]
This guidance already exists and is applicable to any application. We'll update the language to point customers in the vendor direction to follow their best practice probe configuration guidance.
