### ISSUE TITLE
🪲 Bug Report - Reliance on powershell-yaml module does not work when powershell is in constrainedmode

### ISSUE THREAD

**Issue by pagyP** [Azure/Azure-Proactive-Resiliency-Library-v2#203]
## Describe the bug
When powershell is in constrainedmode the install of the powershell-yaml module fails with:
An error has occurred while loading the script module powershell-yaml because it is in a different language mode than the module manifest.  The manifest language mode is constrained language and the module language is fulllanguage

## To Reproduce
Put powershell in constrainedlanguage mode and run install-module powershell-yaml or let it run as part of the data analyser script.

## Expected behaviour
Well, in this situation I suppose the above is the expected behaviour because of the different language modes.  But in locked down environments where powershell is placed into constrainedlanguage mode by policy we need this to work, as in the the module installs correctly.

Anything else we should know to help us troubleshoot this bug?

The customer will not change their security posture to accommodate running of this script, so something in the scripts needs to change.

**Comment by kpoineal** [comment]
As part of our refactor we will be removing the dependency on powershell-yaml so this issue should resolve itself once that is complete.
