### ISSUE TITLE
🪲 Bug Report - Use premium performance block blob storage for high performance workloads with ARG query

### ISSUE THREAD

**Issue by sihbher** [Azure/Azure-Proactive-Resiliency-Library-v2#223]
## Describe the bug
For recommendation "Use premium performance block blob storage for high performance workloads" for storage accounts (https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Storage/storageAccounts/), it says "cannot-be-validated-with-arg" but if I run the following query I can see the tier, or does it refer to a different attribute?

Resources
| where type =~ 'microsoft.storage/storageaccounts'
| extend sku_name=sku.name, tier=sku.tier
|project sku_name, tier, name, kind

**Comment by ejhenry** [comment]
@pinyuko can you take a look at this?

**Comment by pinyuko** [comment]
We are able to see the tier, but we are not able to confirm whether the workload actually needs premium tier. @ejhenry , do you think we should directly list all storage accounts that are not using premium tier? Thanks!

**Comment by ejhenry** [comment]
> We are able to see the tier, but we are not able to confirm whether the workload actually needs premium tier. @ejhenry , do you think we should directly list all storage accounts that are not using premium tier? Thanks!

Thanks for looking at this @pinyuko. As there is an additional step beyond checking the tier to determine what is appropriate for the workload, I think we should leave this as something that cannot be validated with ARG. We don't want to just pull all non-premium storage as that can result in incorrect recommendations.

@sihbher let us know if you think that sounds reasonable.

**Comment by sihbher** [comment]
It makes sense now, thanks
