### ISSUE TITLE
🪲 Bug Report - Errors running 2_wara_data_analyzer.ps1

### ISSUE THREAD

**Issue by ecalalang** [Azure/Azure-Proactive-Resiliency-Library-v2#224]
## Describe the bug

2_wara_data_analyzer.ps1 

Line 124 - Depth 15 is not a parameter for ConvertFrom-Jason
--- $results = Get-Content -Path $JSONFile | ConvertFrom-Json -Depth 15

Line 173  ---- $YAML is missing .Fullname
-- $Script:ServicesYAMLContent += Get-Content -Path $YAML | ConvertFrom-Yaml
This should be
-- $Script:ServicesYAMLContent += Get-Content -Path $YAML.FullName | ConvertFrom-Yaml
Line181 --- Same issue as Line 173

## To Reproduce

Steps to reproduce the behaviour:

1. Fill
2. Me
3. In

## Expected behaviour

A clear and concise description of what you expected to happen without this bug 🙂

## Screenshots 📷
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/32887855/b3530fa5-fb1a-4551-9de3-cae43f8d6ebf)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/32887855/0bca7413-4111-493c-832a-547a7c6cfdb1)

If applicable, add screenshots to help explain your problem. Please feel free to blur/cover any sensitive information.

## Additional context

Anything else we should know to help us troubleshoot this bug?

**Comment by kpoineal** [comment]
@ecalalang Can you confirm what version of Powershell you're running this on for me? The script requires Pwsh7 to run correctly. Thank you!

**Comment by ecalalang** [comment]
Yup, found out what was wrong since I was using my HW refresh machine!!! 

All good, I was still able to make it work with the old Powershell Version !!!
