### ISSUE TITLE
💡 Feature Request - Custom Filtering Scenario

### ISSUE THREAD

**Issue by terrymandin** [Azure/Azure-Proactive-Resiliency-Library-v2#225]
## Describe the solution you'd like

Below is a complex query I needed to do for my WARA.  Please consider adding this functionality to an upcoming release.

(     In a resource group with a name containing "PRD" or "PROD"
      OR
      A resource name containing "PRD" or "PROD"
)
OR
(     A virtual machine name that starts with “AZ-[W,L][D,T,P]”. The W or L is Windows or Linux, and the DRP is Dev/Test/Prod.
)

## Describe alternatives you've considered

I imported the ImpactedResources into MS Access and did the complex querying there.  e.g.:

```
SELECT ImpactedResources.resourceType, ImpactedResources.name, ImpactedResources.id
FROM ImpactedResources
WHERE (((((([ImpactedResources].[id]) Like "*PRD*" Or ([ImpactedResources].[id]) Like "*PROD*")) Or ((([ImpactedResources].[resourceType])="Microsoft.Compute/virtualMachines") And ((UCase([ImpactedResources].[name])) Like "AZ-[LW][P]*")))=True))
GROUP BY ImpactedResources.resourceType, ImpactedResources.name, ImpactedResources.id
ORDER BY ImpactedResources.name;
```

**Comment by oZakari** [comment]
Hey @terrymandin, could you clarify the ask here? This looks like a query for SQL and not for KQL based upon the operators you're using.
