### ISSUE TITLE
❓👂 Are Function Apps purposefully excluded from the Health Check recommendation 

### ISSUE THREAD

**Issue by basimolimajeed** [Azure/Azure-Proactive-Resiliency-Library-v2#228]
## Question/Feedback

The query azure-resources/Web/sites/kql/fd049c28-ae6d-48f0-a641-cc3ba1a3fe1d.kql checks for app services that do not have Health Check path configured. However it does not show Function Apps that do not have Health check path configured. Is this done deliberately or an oversight? I think Function apps that support Health check path should be considered and returned by the query if it matches since this doc mentions them in the context of Health Check https://learn.microsoft.com/en-us/azure/app-service/monitor-instances-health-check?tabs=dotnet#enable-health-check

## Possible Answers/Solutions?

If we want to extend the health check path to function apps then the query needs a minor change. I can submit a PR if needed but wanted to make sure whether the intention was to include them or leave them out.

**Comment by ejhenry** [comment]
@parthshiras please review

**Comment by ejhenry** [comment]
@basimolimajeed the omission of Function Apps was not intentional. If you'd like to submit the PR you mentioned, that would be great.
