### ISSUE TITLE
💡 Feature Request - Add new VM APRL checking Linux agent version

### ISSUE THREAD

**Issue by pinyuko** [Azure/Azure-Proactive-Resiliency-Library-v2#229]
## Describe the solution you'd like

CSA lanicola suggested to add a new VM APRL about checking Linux agent version [Azure Linux VM Agent overview - Azure Virtual Machines | Microsoft Learn](https://learn.microsoft.com/en-us/azure/virtual-machines/extensions/agent-linux).
 
She suggested this because a customer recently had downtime and it was due to the fact that the agent was outdated, and a live migration did not work even though everything was in place this was a single point of failure.

## Describe alternatives you've considered

N/A

## Additional context

[Add any other context or screenshots about the feature request here. 📷](https://sirona.visualstudio.com/Solutions/_workitems/edit/729671)

**Comment by oZakari** [comment]
Hi @pinyuko, just to confirm so we don't duplicate effort. Are you or the CSA currently working on adding this one?

**Comment by pinyuko** [comment]
Hi @oZakari 
No, we are not working on it. I'm just submitting this feedback for the CSA from VBD feedback. 
Please kindly include this in your sprint discussion. Thank you!

**Comment by ejhenry** [comment]
cc @hannah-leland
