### ISSUE TITLE
🪲 Bug Report - There is duplicated recommendationId

### ISSUE THREAD

**Issue by tksh164** [Azure/Azure-Proactive-Resiliency-Library-v2#233]
## Describe the bug

Seems that two KQL files are there with the same file name and the `recommendationId`. Is this expected?

Filename: `dc55be60-6f8c-461e-a9d5-a3c7686ed94e.kql`

- https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/main/azure-specialized-workloads/avd/kql/dc55be60-6f8c-461e-a9d5-a3c7686ed94e.kql
- https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/main/azure-resources/Storage/storageAccounts/kql/dc55be60-6f8c-461e-a9d5-a3c7686ed94e.kql

## To Reproduce

n/a

## Expected behaviour

n/a

## Screenshots 📷

n/a

## Additional context

n/a

**Comment by oZakari** [comment]
Hi @tksh164, you are correct, there should not be duplicate recommendation GUIDs anywhere including specialized workloads. I will work on cleaning this up.
