### ISSUE TITLE
🪲 Bug Report - Different KQL file name and recommendatinId in it.

### ISSUE THREAD

**Issue by tksh164** [Azure/Azure-Proactive-Resiliency-Library-v2#234]
## Describe the bug

The following KQL file has an different `recommendationId` from the file name. Is this expected?

- https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/main/azure-specialized-workloads/sap/kql/b60ae773-9917-4bca-8a42-7cb45365a917.kql

```sql
| project recommendationId = "df0ff862-814d-45a3-95e4-4fad5a244ba6", name, id, tags, param1=strcat("AffectedDisks: ", disks)
```

## To Reproduce

n/a

## Expected behaviour

n/a

## Screenshots 📷

n/a

## Additional context

n/a

**Comment by ejhenry** [comment]
@Azure/aprl-sap please review
