### ISSUE TITLE
🪲 Bug Report - recommendation, automationAvailable data type

### ISSUE THREAD

**Issue by ReneHezser** [Azure/Azure-Proactive-Resiliency-Library-v2#249]
## Describe the bug

The documentation is inconsistent, as it defines a boolean for the property, but the values are `no`or `arg`.

Key | Example Value | Data Type | Allowed Values | Description
-- | -- | -- | -- | --
automationAvailable | false | Boolean | no, arg | Indicates whether automation is available for validating the recommendation

</body>
</html>

</body>
</html>

## To Reproduce

Steps to reproduce the behaviour:

[Recommendation Structure
](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing/create-content/create-recommendations/#recommendation-structure)

## Expected behaviour

Consistent information

**Comment by oZakari** [comment]
Thanks @ReneHezser, this one is on me so will fix.
