### ISSUE TITLE
❓👂 Question/Feedback - "Monitor Private DNS Zones health and set up alerts" unclear description

### ISSUE THREAD

**Issue by jdmsoss** [Azure/Azure-Proactive-Resiliency-Library-v2#261]
## Question/Feedback

The APRL recommendation [Monitor Private DNS Zones health and set up alerts](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/privateDnsZones/#monitor-private-dns-zones-health-and-set-up-alerts) has an unclear description.

Here's the description:

`The records in a private DNS zone are only resolvable from linked virtual networks. You can link a private DNS zone to multiple networks and enable autoregistration to manage DNS records for virtual machines automatically.`

**How do you establish a link between this recommendation and its description?**

## Possible Answers/Solutions?

I suggest to provide a consistent description about DNS Zones health monitoring/alerting.

**Comment by ejhenry** [comment]
@Azure/aprl-networking please review

**Comment by ehaslett** [comment]
I agree the description is pretty unclear and not linked in a good way to the recommendation. While I am not volunteering at this time, we should have this assigned to improve clarity and align to existing documentation. I looked for the original author in the previous repo but cannot determine who it was, but it might be worth asking for their assistance if available

**Comment by ejhenry** [comment]
@Azure/aprl-networking please review

**Comment by ehaslett** [comment]
I am covering this update via another bug report. Should be updated by end of week (August 30th).
