### ISSUE TITLE
❓👂 Question/Feedback - Appears to be duplicate recommendations for deploying across zones/regions for AVD

### ISSUE THREAD

**Issue by judyer28** [Azure/Azure-Proactive-Resiliency-Library-v2#278]
## Question/Feedback

There are 2 recommendations for deploying across zones/regions for AVD that seem almost identical.  Not sure if this was intended?

https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-specialized-workloads/avd/#deploy-two-or-more-domain-controllers-on-azure-vms-across-availability-zones-in-the-avd-region

https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-specialized-workloads/avd/#deploy-domain-controllers-on-azure-vms-across-availability-zones-in-the-avd-region

## Possible Answers/Solutions?

Seems like they could just be consolidated into one recommendation.

**Comment by ejhenry** [comment]
@Azure/aprl-avd please review

**Comment by moisesjgomez** [comment]
These can be consolidated into 1. Thinking we can keep the recommendation with "two or more" as it's the more specific one.

cc: @swathibhat1 @danycontre

**Comment by oZakari** [comment]
Thanks @moisesjgomez or someone from @Azure/aprl-avd be able to create a PR with these changes?

**Comment by oZakari** [comment]
Closed by #322
