### ISSUE TITLE
❓👂 Question/Feedback - "Configure Diagnostic Settings for all network security groups" provides an unclear explanation.

### ISSUE THREAD

**Issue by NaotakaKawakami** [Azure/Azure-Proactive-Resiliency-Library-v2#294]
## Question/Feedback
In the following APRL, it is recommended to enable NSG diagnostics settings, which allows the collection of the following logs:
However, it is not clearly stated how this contributes to reliability improvement.

https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/networkSecurityGroups/#configure-diagnostic-settings-for-all-network-security-groups

https://learn.microsoft.com/en-us/azure/virtual-network/virtual-network-nsg-manage-log#enable-logging
> Event: Entries are logged for which NSG rules are applied to virtual machines, based on MAC address.
> Rule counter: Contains entries for how many times each NSG rule is applied to allow or deny traffic. The status for these rules is collected every 300 seconds.

## Possible Answers/Solutions?
I suggest to describe why this is related to reliability.

**Comment by oZakari** [comment]
@Azure/aprl-networking please review.

**Comment by oZakari** [comment]
As confirmed by @maheshbenke, will close this out for now. @NaotakaKawakami, if you have any additional concerns, please don't hesitate to reach out as we appreciate your feedback!
