### ISSUE TITLE
🪲 Bug Report - Failed insert charts from Excel on slide 17

### ISSUE THREAD

**Issue by tksh164** [Azure/Azure-Proactive-Resiliency-Library-v2#295]
## Describe the bug

Inserting charts failed from the Excel file on the slide 17 that was generated by 3_wara_reports_generator.ps1 (version 2.0.5).

## To Reproduce

1. Run the `1_wara_collector.ps1`.
2. Run the `2_wara_data_analyzer.ps1`.
3. Run the `3_wara_reports_generator.ps1`.

## Expected behaviour

The charts are inserted from the Excel file.

## Screenshots 📷

![image](https://github.com/user-attachments/assets/e493365f-cad5-4634-b21e-68e5169a04a6)

## Additional context

When processing the slide 17, `$Global:Ex` was null.

https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/95246b37700ceb141ab7dda100900416f64738db/tools/3_wara_reports_generator.ps1#L449

So, doing copy and paste the charts will fail.

https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/95246b37700ceb141ab7dda100900416f64738db/tools/3_wara_reports_generator.ps1#L455-L457

https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/95246b37700ceb141ab7dda100900416f64738db/tools/3_wara_reports_generator.ps1#L471-L473

**Additional notes:**

The code of slide manipulation needs refactoring. It has unnecessary complexity. It will lead to mis-modification and increase maintenance efforts.

Current:
https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/95246b37700ceb141ab7dda100900416f64738db/tools/3_wara_reports_generator.ps1#L443-L483

Example:

```powershell
$Slide17 = $pres.Slides(17)

# Update the notice label
$noticeLabelName = 'TextBox 1'
$TargetShape = $Slide17.Shapes($noticeLabelName)
$TargetShape.TextFrame.TextRange.Text = $AUTOMESSAGE

if ($CoreDebugging) { ('PPT_Thread - ' + (get-date -Format 'yyyy-MM-dd HH:mm:ss') + ' - Info - Editing Slide 17 - Looking Charts in Excel File...') | Out-File -FilePath $LogFile -Append }
$chartWorksheetName = 'Charts'
$WS2 = $Global:Ex.Worksheets($chartWorksheetName)

# Copy "Per services/WAF area" chart from the Excel file.
if ($CoreDebugging) { ('PPT_Thread - ' + (get-date -Format 'yyyy-MM-dd HH:mm:ss') + ' - Info - Editing Slide 17 - Replacing Chart 1..') | Out-File -FilePath $LogFile -Append }
$sampleChartNamePerServicesWafArea = 'Chart 2'
$chartNamePerServicesWafArea = 'ChartP0'
$Slide17.Shapes($sampleChartNamePerServicesWafArea).Delete()
if ($Heavy) {Start-Sleep -Milliseconds 500} else {Start-Sleep -Milliseconds 100}
$WS2.ChartObjects($chartNamePerServicesWafArea).Copy()
if ($Heavy) {Start-Sleep -Milliseconds 500} else {Start-Sleep -Milliseconds 100}
[void] $Slide17.Shapes.Paste()
Start-Sleep 2
$targetShape = $Slide17.Shapes($chartNamePerServicesWafArea)
$targetShape.IncrementLeft(240)

# Copy "Per resiliency category" chart from the Excel file.
if ($CoreDebugging) { ('PPT_Thread - ' + (get-date -Format 'yyyy-MM-dd HH:mm:ss') + ' - Info - Editing Slide 17 - Replacing Chart 2..') | Out-File -FilePath $LogFile -Append }
$sampleChartNamePerResiliencyCategory = 'Chart 4'
$chartNamePerResiliencyCategory = 'ChartP1'
$Slide17.Shapes($sampleChartNamePerResiliencyCategory).Delete()
if ($Heavy) {Start-Sleep -Milliseconds 500} else {Start-Sleep -Milliseconds 100}
$WS2.ChartObjects($chartNamePerResiliencyCategory).Copy()
if ($Heavy) {Start-Sleep -Milliseconds 500} else {Start-Sleep -Milliseconds 100}
[void] $Slide17.Shapes.Paste()
Start-Sleep 2
$targetShape = $Slide17.Shapes($chartNamePerResiliencyCategory)
$targetShape.IncrementLeft(-260)
$targetShape.IncrementTop(45)
```

**Comment by Claudio-Merola** [comment]
Hello @tksh164 

Can you check and test the version of the script present in the dev-tools branch?

As we've practically refactored the 3rd script there
