### ISSUE TITLE
🪲 Bug Report - Some AFW ARG queries return inaccurate/incorrect results for VWAN secure hubs

### ISSUE THREAD

**Issue by ehaslett** [Azure/Azure-Proactive-Resiliency-Library-v2#31]
## Describe the bug

The following AFW ARG queries return results for VWAN associated AFWs in secure hubs, and should not:

https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/azureFirewalls/#deploy-azure-firewall-across-multiple-availability-zones

https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/azureFirewalls/#configure-ddos-protection-on-the-azure-firewall-vnet

## To Reproduce

Steps to reproduce the behaviour:

1. Deploy VWAN and a VWAN secure hub with AFW
2. Run either wara-arg-runner.ps1 or wara_collector.ps1 and wara_data_analyzer.ps1 against this sub
3. Note the results for the above ARG queries. 
4.

## Expected behaviour

The queries should not return results for AFWs in a VWAN secure hub

## Screenshots 📷

N/A

## Additional context

Anything else we should know to help us troubleshoot this bug?

**Comment by ejhenry** [comment]
cc @JefferyMitchell

**Comment by oZakari** [comment]
Hey @JefferyMitchell, assigned to you for the time being but feel free to reassign when you have CSA allocated.

**Comment by ehaslett** [comment]
Closing this out. The DDOS APRL guidance has been removed. The ARG query for the following has already been updated to exclude virtual hubs:
https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/azureFirewalls/#deploy-azure-firewall-across-multiple-availability-zones
