### ISSUE TITLE
👂 Feedback - Sticking out resource type name in ARPL document

### ISSUE THREAD

**Issue by tksh164** [Azure/Azure-Proactive-Resiliency-Library-v2#315]
## Question/Feedback

The long resource type names are sticking out from the left menu area. It is sometimes covered by the content of the right area.

https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/expressRouteGateways/

![image](https://github.com/user-attachments/assets/5542c665-77e1-4468-87f0-28924013fb3a)

## Possible Answers/Solutions?

There are some solutions, I think. For example:

- Add `overflow-wrap: break-word` to `gdoc-nav__entry` CSS class.
- Increase the left area width.

![image](https://github.com/user-attachments/assets/77729faa-9d12-4654-9d97-c29c68782b06)

**Comment by oZakari** [comment]
Hey @tksh164, thanks! If you want to open a PR with this approach, happy to incorporate it!

**Comment by tksh164** [comment]
Fixed by #329
