### ISSUE TITLE
👂 Feedback - Empty recommendationTypeId

### ISSUE THREAD

**Issue by tksh164** [Azure/Azure-Proactive-Resiliency-Library-v2#325]
## Feedback

About `recommendationTypeId`, [Recommendation Structure](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing/create-content/create-recommendations/#recommendation-structure) says `null until updated by the Azure Advisor team`. But the following recommendations have no value. Is this expected?

- 4b1a45af-d35f-442d-922a-a3e7b6052de1

    https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/906eedf4e08a51325b9921c92d303786d46878c8/azure-specialized-workloads/avd/recommendations.yaml#L297-L299

- 7b170ddd-5770-4945-9bc3-cd1ccf5f8672

    https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/906eedf4e08a51325b9921c92d303786d46878c8/azure-specialized-workloads/avd/recommendations.yaml#L376-L378

## Possible Answers/Solutions?

If it is expected, nothing to do. If not expected, set `null` as the value.

**Comment by ejhenry** [comment]
Good catch @tksh164, these should have 'null' as the value.
