### ISSUE TITLE
WARA Collector missing SQL Resources

### ISSUE THREAD

**Issue by humblejay** [Azure/Azure-Proactive-Resiliency-Library-v2#342]
## Describe the bug

WARA Collector did not find SQL MI instances and so fail to generate recommendations.  If the query is executed manually the resources are found with associated recommendation Ids.

## To Reproduce

Steps to reproduce the behaviour:

1. Run 1_wara_collector.ps1 on subscription having SQL MI,  configured not to have Geo replication.
2. Check the output to see if SQL instances and recommendations are present
3. Execute[ APRL query](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Sql/servers/#use-active-geo-replication-to-create-a-readable-secondary-in-another-region) to confirm query is working.

## Expected behaviour

The wara collector script should pick up the SQL MI and associate specific recommendations for it. 

## Screenshots 📷

If applicable, add screenshots to help explain your problem. Please feel free to blur/cover any sensitive information.

## Additional context

Anything else we should know to help us troubleshoot this bug?

**Comment by tksh164** [comment]
Hi @humblejay, the [ARG query](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Sql/servers/#use-active-geo-replication-to-create-a-readable-secondary-in-another-region) that you mentioned seems for **SQL Database**, not **SQL Managed Instance**.

![image](https://github.com/user-attachments/assets/be661c45-9d94-42ff-b5b6-3d37c618e4ad)

Actually, there are no recommendations for SQL Managed Instances in APRL.

- https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/main/azure-resources/Sql/managedInstances/_index.md


> If the query is executed manually the resources are found with associated recommendation Ids.

What query did you executed manually?

**Comment by oZakari** [comment]
@humblejay, as @tksh164 noted, this query is not applicable to SQL Managed Instances so closing as this is the expected behavior.
