### ISSUE TITLE
🪲 Bug Report - wara_collector script does not allow for Air Gap Clouds

### ISSUE THREAD

**Issue by Commochief** [Azure/Azure-Proactive-Resiliency-Library-v2#348]
## Describe the bug

The AzureEnvironment variable does not allow for the Air Gap Clouds and hardcodes the environment metadata instead of pulling those from the AzureEnvironment.

## To Reproduce

Line 102 - [ValidateSet('AzureCloud', 'AzureUSGovernment')] 
Line 103 -$AzureEnvironment = 'AzureCloud',

Line 491 - if ($AzureEnvironment -eq 'AzureUSGovernment') {
                      $BaseURL = 'management.usgovcloudapi.net'
                    } else {
                      $BaseURL = 'management.azure.com'
                    }

## Expected behaviour

Allow use of USSEC and USNAT Azure Environment variables and pull the management Api from the environment instead of hardcoding.

Reach out to me for endpoint details.

**Comment by oZakari** [comment]
@Azure/aprl-wara-tools please review.

**Comment by Monte-Hazboun** [comment]
I can put in a PR to fix this.   We'll need to have documentation on the federal side that the USSEC and USNAT environments need to be added before running the script since we can't actually include adding those environments in the scripts.

**Comment by kpoineal** [comment]
Closing this issue since there is a PR for it already.
