### ISSUE TITLE
🪲 Bug Report - aks-1 - false positive

### ISSUE THREAD

**Issue by ReneHezser** [Azure/Azure-Proactive-Resiliency-Library-v2#36]
## Describe the bug

If AKS is deployed to only one AZ, it will not appear in the result.

## To Reproduce

Steps to reproduce the behaviour:

1. Deploy AKS to one AZ

## Expected behavior

The cluster should be a result, as it is not deployed to more than one zone.

## Screenshots 📷

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/5988767/ee86fb48-7c61-4b7d-b0b9-9fb465798f31)

**Comment by ejhenry** [comment]
cc @ibersanoMS

**Comment by ibersanoMS** [comment]
The query was written to only detect clusters that do not have any AZs, but it can be updated to return those that have 1 or less

**Comment by ejhenry** [comment]
@ReneHezser - #61 has been merged to resolve this issue. Thanks for updating the query @tksh164!

cc @ibersanoMS
