### ISSUE TITLE
🪲 Bug Report - Advisor versus APRL category naming correction - High Availability

### ISSUE THREAD

**Issue by humblejay** [Azure/Azure-Proactive-Resiliency-Library-v2#360]
## Describe the bug

The High Availability Advisor recommendations in generated Excel are categorized as "HighAvailability" while the APRL generated recommendations use "High Availability" with a space.  It create duplicate category in the Pivot Charts and PPT.

## To Reproduce

Steps to reproduce the behaviour:

1. Run [2_wara_data_analyzer.ps1](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/main/tools/2_wara_data_analyzer.ps1) on Json created by [1_wara_collector.ps1](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/main/tools/1_wara_collector.ps1)
2. Check Pivot table in the generated Excel, it shows both categories as seperate lines in the table.

## Expected behaviour

Both refer to one category so should be combined together either by changing APRL convention or Advisor.

## Screenshots 📷
<img width="386" alt="image" src="https://github.com/user-attachments/assets/d6eac09d-5249-4540-9659-42a139d938d7">

If applicable, add screenshots to help explain your problem. Please feel free to blur/cover any sensitive information.

## Additional context

Anything else we should know to help us troubleshoot this bug?

**Comment by ejhenry** [comment]
Thanks for opening this issue @humblejay, we've added to our backlog to get addressed.

**Comment by Claudio-Merola** [comment]
Issue is still present
