### ISSUE TITLE
🪲 Bug Report - On Demand Capacity Recommendations false positives

### ISSUE THREAD

**Issue by chrislittle** [Azure/Azure-Proactive-Resiliency-Library-v2#393]
## On Demand Capacity Reservations false positives

It looks like the scripts are recommending [Reserve Compute Capacity for critical workloads](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Compute/virtualMachines/#reserve-compute-capacity-for-critical-workloads) for all VM's in a customer environment. The use of reserved compute cannot be broad strokes for all workloads as it solves very specific use cases. for example, reserving capacity in a DR region to make sure capacity is available when needed.

**Comment by ejhenry** [comment]
@hannah-leland can you look into this with PG? Need clarification on what exactly the recommendation should be so that we can align the ARG query. As @chrislittle points out, the ARG query currently identifies all VMs as applicable for the recommendation.

**Comment by ejhenry** [comment]
@chrislittle - @hannah-leland has confirmed with PG that the current recommendation and ARG query align with their perspective. As we are scoping the query to just the workload, the guidance is that all VMs in a mission-critical workload should have a CR. We are going to add a separate recommendation for CRs in a DR region.
