### ISSUE TITLE
🪲 Bug Report - File Not Found not surfaced as an error

### ISSUE THREAD

**Issue by jszubryt** [Azure/Azure-Proactive-Resiliency-Library-v2#398]
## Describe the bug

If the spreadsheet file for input isn't found, the script doesn't surface the error. The -debugging parameter has to be added to see the error in the log

## To Reproduce

Steps to reproduce the behaviour:

1. Use the .\ in the parameter for the file that is in the C:\WARA folder when you are running the script
2. The script shows it executes successfully and provides the .PPTX and .DOCX files in the output
3. Neither the PowerPoint or Word documents are created

## Expected behaviour

The script should indicate the input wasn't found and not executed successfully.

## Screenshots 📷
![image](https://github.com/user-attachments/assets/f818c0b9-faf4-4688-828f-c7a90a6e2ddf)

If applicable, add screenshots to help explain your problem. Please feel free to blur/cover any sensitive information.

## Additional context

The example on the APRL site showed using .\ and I found I needed to specify C:\WARA

**Comment by ejhenry** [comment]
@jszubryt in your screenshot it looks as though there is only the action plan spreadsheet in the WARA directory. The reports generator script also expects the template files to be in the same directory with their default names. The template file parameters are optional if you want to use a different location or filename.

**Comment by ejhenry** [comment]
Testing with @jszubryt and was able to reproduce the issue when using the template file parameters. When using a template file parameter both the path to the template and the action plan spreadsheet must contain the full file path.
