### ISSUE TITLE
🪲 Bug Report - KQL For resourceGroups is not working

### ISSUE THREAD

**Issue by rodrigosantosms** [Azure/Azure-Proactive-Resiliency-Library-v2#406]
## Describe the bug

The query is not returning impacted resources even though I had resourceGroup and their resources in different locations. 

Ensure Resource Group and its Resources are located in the same Region
https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Resources/resourceGroups/#ensure-resource-group-and-its-resources-are-located-in-the-same-region

## To Reproduce

1 - Run the KQL

## Expected behaviour

Users expect to see resources not deployed in the same region as their ResourceGroups to be listed by the query.

## Additional context

no.

**Comment by tksh164** [comment]
I tried the KQL and it works correctly. However, the KQL/Resource Graph is unstable. Because the KQL sometimes returns correct result, but sometimes not in my environment. To reproduce, click **Run Query** button repeatedly.

![image](https://github.com/user-attachments/assets/c644894f-c6fb-4298-b3ff-4bcb92570a87)

![aprl-issues-406](https://github.com/user-attachments/assets/757e1b6d-4bfd-4ac6-8016-c8f00112cc84)

**Comment by tksh164** [comment]
I'm not sure, why current KQL unstable. But I rewrote a KQL, this KQL seems stable. I will create a PR if this KQL is to be stable in your environment.

```sql
resourcecontainers
| where type =~ "Microsoft.Resources/subscriptions/resourceGroups"
| project resourceGroupId = tolower(id), resourceGroupLocation = location
| join kind = inner (
    resources
    | where location !~ "Global" and             // Exclude global resources
        resourceGroup !~ "NetworkWatcherRG" and  // Exclude resources in the NetworkWatcherRG
        id has "/resourceGroups/"                // Exclude resources not in a resource group
    | project id, name, tags, resourceGroup, location, resourceGroupId = tolower(strcat_array(array_slice(split(id, "/"), 0, 4), "/"))
    )
    on resourceGroupId
| where resourceGroupLocation !~ location
| project
    recommendationId = "98bd7098-49d6-491b-86f1-b143d6b1a0ff",
    name,
    id,
    tags,
    param1 = strcat("resourceLocation: ", location),
    param2 = strcat("resourceGroupLocation: ", resourceGroupLocation),
    param3 = strcat("resourceGroup: ", resourceGroup)
```
