### ISSUE TITLE
🪲 Bug Report - False Positive for Configure DDoS Protection on the Azure Firewall VNet due to character case

### ISSUE THREAD

**Issue by judyer28** [Azure/Azure-Proactive-Resiliency-Library-v2#42]
## Describe the bug

The KQL query for [Configure DDoS Protection on the Azure Firewall VNet](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/azureFirewalls/#configure-ddos-protection-on-the-azure-firewall-vnet) produces a false positive if there are upper\lower case inconsistencies in the VNET IDs being joined.  For example the join in the KQL query will fail to recognize the following difference in the IDs being joined:
/resourceGroups/my-resource-group-1/
/resourceGroups/MY-RESOURCE-GROUP-1/

## Expected behaviour

The join should disregard case of the ID

## Additional context

I suggest changing the query to make the ID lowercase before performing the join.  Something like this:

// Azure Resource Graph Query
// List all in-scope Azure Firewall resources, where the VNet is not associated to a DDoS Protection Plan
resources
| where type == "microsoft.network/azurefirewalls"
| mv-expand properties.ipConfigurations
| project name, firewallId = id, vNet = **tolower**(substring(properties_ipConfigurations.properties.subnet.id, 0, indexof(properties_ipConfigurations.properties.subnet, "/subnet") - 7)), tags
| join kind=fullouter (
    resources
    | where type == "microsoft.network/ddosprotectionplans"
    | mv-expand properties.virtualNetworks
    | extend vNet = **tolower**(tostring(properties_virtualNetworks.id))
    | project ddosProtectionPlan = id, vNet
    )
    on $left.vNet == $right.vNet
| where ddosProtectionPlan == ''
| project recommendationId = "1b2dbf4a-8a0b-5e4b-8f4e-3f758188910d", name, id = firewallId, tags, param1 = "ddosProtectionPlan:false"

**Comment by ejhenry** [comment]
@Azure/aprl-networking please review

**Comment by tksh164** [comment]
Fixed #67
