### ISSUE TITLE
💡 Feature Request - Check minimum TLS version for Service Bus Namespace

### ISSUE THREAD

**Issue by IgnacioAguirre** [Azure/Azure-Proactive-Resiliency-Library-v2#420]
## Describe the solution you'd like

In APRL repo for ServiceBus/namespaces ( we should have a recommendation on checking that the minimum TLS version in Service Bus should be higher or equal to TLS v1.2.

APRL: https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/ServiceBus/namespaces/
Doc: https://learn.microsoft.com/en-us/azure/service-bus-messaging/transport-layer-security-configure-minimum-version

You can check this with ARG query:
resources
| where type == "microsoft.servicebus/namespaces"
| where properties.minimumTlsVersion != "1.2" and properties.minimumTlsVersion != "1.3"
| project name, resourceGroup, subscriptionId, properties.minimumTlsVersion

**Comment by miguellords** [comment]
maybe this will help
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
If you don't have the c compliator, install it.(gcc or clang)
