### ISSUE TITLE
🪲 Bug Report - Tools - WARA Collector - Tenant wide not working

### ISSUE THREAD

**Issue by Springstone** [Azure/Azure-Proactive-Resiliency-Library-v2#435]
## Describe the bug

The tenant wide collection of data (all subscriptions) is blocked by logic requiring either subscription Ids or resource group Ids.

This doesn't work:

```
Run against all subscriptions in tenant "00000000-0000-0000-0000-000000000000":
.\1_wara_collector.ps1 -TenantID 00000000-0000-0000-0000-000000000000
```

## To Reproduce

Steps to reproduce the behaviour:

1. Provide only Tenant Id to the 1_wara_collector.ps1

## Expected behaviour

Should be able to collect all data at Tenant level.

## Screenshots 📷

![image](https://github.com/user-attachments/assets/9a7854e5-31fd-4c60-9155-d2630115d7a0)

## Additional context

Anything else we should know to help us troubleshoot this bug?

**Comment by kpoineal** [comment]
This is by design. WARA is meant to be workload specific, so we expect users to explicitly define their scopes.
