### ISSUE TITLE
🪲 Bug Report - Replicate VMs using Azure Site Recovery KQL should not return trusted launch VMs 

### ISSUE THREAD

**Issue by judyer28** [Azure/Azure-Proactive-Resiliency-Library-v2#44]
## Describe the bug

Azure Site Recovery does not support Trusted Launch VMs.  See [here](https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch#unsupported-features).  The KQL query for [Replicate VMs using Azure Site Recovery](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Compute/virtualMachines/#replicate-vms-using-azure-site-recovery) should ignore or not return results that are not currently supported by Site Recovery.

## To Reproduce

Steps to reproduce the behaviour:

1. Create a trusted launch VM
2. Go to Disaster recovery and see that trusted launch is not supported

## Expected behaviour

Return a list of VMs that are supported by Site Recovery and do not currently have it enabled

## Screenshots 📷

If applicable, add screenshots to help explain your problem. Please feel free to blur/cover any sensitive information.

## Additional context

I suggest updating the KQL query to ignore VMs with the following property setting:  "securityType": "TrustedLaunch"

**Comment by ejhenry** [comment]
cc @pinyuko

**Comment by ejhenry** [comment]
#65 merged, closing issue
