### ISSUE TITLE
🪲 Bug Report - Ensure the Backend Pool contains at least two instances KQL query does not catch Basic configuration

### ISSUE THREAD

**Issue by judyer28** [Azure/Azure-Proactive-Resiliency-Library-v2#46]
## Describe the bug

The KQL query for [Ensure the Backend Pool contains at least two instances](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/loadBalancers/#ensure-the-backend-pool-contains-at-least-two-instances) does not catch Basic Load Balancers with one backend pool containing only one VM.

## To Reproduce

Steps to reproduce the behaviour:

1. Create a VM with Basic SKU Public IP
2. Create Basic Load Balancer with backend pool containing the VM
3. Run KQL query and see that the Load Balancer is not captured

## Expected behaviour

KQL query should catch all LB with backends that have less than two instances

## Screenshots 📷

If applicable, add screenshots to help explain your problem. Please feel free to blur/cover any sensitive information.

## Additional context
 The query looks for backendAddressPools.properties.loadBalancerBackendAddresses but with this configuration, that property does not exist.  It only has the property  backendAddressPools.properties.backendIPConfigurations.

**Comment by ejhenry** [comment]
@Azure/aprl-networking please review

**Comment by jimays-avila** [comment]
@judyer28 should we add recommendations around basic load balancers?  Basic load balancers are free, do not have an SLA, and are not recommendation for production.

**Comment by judyer28** [comment]
@jimays-avila good point.  Since we do have a recommendation to use Standard load balancers over Basic, maybe this is not needed.  Only potential issue I see is with workflow when running the checks.  For example, user runs through all LB checks, sees they need to upgrade to Standard, but does not get a recommendation for backend pool.  User then upgrades LB to standard but still without two nodes in backend pool.  Would need to rerun checks to see this recommendation that was not caught the first time around.

**Comment by jchancellor-ms** [comment]
Basic sku load-balancers will already get flagged here.  I'll also see if there is a way to update the KQL to also catch basic sku's LB's with fewer than two instances in the backend pools.

**Comment by jchancellor-ms** [comment]
This is going to be a bit of a challenge.  The resource graph doesn't contain backend pool details for basic load-balancers.  I'll see if I can query it from the other direction, but it may get complex fast.  If that doesn't work, the fallback may be to just flag all the basic sku load balancers with a parameter note advising that their backend pools be checked manually.  I'll also talk to Tim to see if there is a way we can work with the PG to get the backend pool details pushed to the resource graph.

**Comment by judyer28** [comment]
Sounds like a good plan Jon.  Thanks for investigating.
