### ISSUE TITLE
🪲 Bug Report - Powerpoint and Word file not generated

### ISSUE THREAD

**Issue by DevOpsStyle** [Azure/Azure-Proactive-Resiliency-Library-v2#467]
## Describe the bug

The 3_wara_reports_generator.ps1 doesn't generate the powerpoint and word files

## To Reproduce

Steps to reproduce the behaviour:

.\3_wara_reports_generator.ps1 -ExcelFile 'C:\WARA_Script\WARA Action Plan 2024-03-07_16_06.xlsx' -CustomerName 'ABC Customer' -WorkloadName 'SAP On Azure' -Heavy -PPTTemplateFile 'C:\Templates\Template.pptx' -WordTemplateFile 'C:\Templates\Template.docx'

## Expected behaviour

PPTX and DOCX files generated

## Screenshots 📷

![Image](https://github.com/user-attachments/assets/7920ea2a-7f0d-4807-98f0-5d5cf60b4468)
![Image](https://github.com/user-attachments/assets/08843a6a-4140-43cb-b1d3-d5609fb45f75)

## Additional context

Tried on 2 differet computers with Office installed

**Comment by kpoineal** [comment]
Can you reach out to me on teams and we can find some time to review this? Thanks!

**Comment by DevOpsStyle** [comment]
@kpoineal Thank you kpoineal, feel free to ping me when you are available.

**Comment by kpoineal** [comment]
@DevOpsStyle I'm not sure who I should be reaching out to :D

At any rate I already have a fix in for this that will be released with the next patch I'm pushing this week. Thanks!

**Comment by kpoineal** [comment]
@DevOpsStyle Please give the latest version a shot and see if it works now. Thank you!

**Comment by kpoineal** [comment]
@DevOpsStyle This should be fixed in the latest release. Please re-open if you continue to have issues. Thank you!
