### ISSUE TITLE
🪲 Bug Report - Recovery Services Vault : "Migrate from classic alerts ..." false positive

### ISSUE THREAD

**Issue by jdmsoss** [Azure/Azure-Proactive-Resiliency-Library-v2#470]
## Describe the bug

[Migrate from classic alerts to built-in Azure Monitor alerts for Azure Recovery Services Vaults](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/RecoveryServices/vaults/#migrate-from-classic-alerts-to-built-in-azure-monitor-alerts-for-azure-recovery-services-vaults) ARG query produce false positives.

## To Reproduce

Steps to reproduce the behaviour:

1. Create a new Recovery Services Vault (without specific alerting configuration / strategy)
2. Run the ARG query
3. False positive!

## Expected behaviour

This recommendation should only return Recovery Services Vault with classic alert configured. If classic alerts aren't configured, don't return the vault in the recommendation.

## Additional context

The condition logic around `monitoringSettings` property (*IF monitoringSettings isnull THEN classic alert is enabled*) doesn't seem to be the best approach. Because when I configure Azure Alert and not Classic Alert for my vault, `monitoringSettings` still doesn't exist (so still a false positive).

**Comment by ejhenry** [comment]
Thanks for opening this bug @jdmsoss. We'll disable this recommendation query until we have a working version.
