### ISSUE TITLE
💡 Feature Request - Add recommendations for Front Door Classic

### ISSUE THREAD

**Issue by judyer28** [Azure/Azure-Proactive-Resiliency-Library-v2#50]
## Describe the solution you'd like

Front Door Classic is not set to retire until March 31, 2027.  It would be good to have recommendations for users currently using FD Classic.  The recommendations for AFD Standard\Premium mostly apply but would need updates to ARG queries and links to documentation.

## Describe alternatives you've considered

Create a section under Network->Front Door (Classic) that contains specific recommendations and queries for classic.

## Additional context

I ran through the existing recommendations for AFD and here is a quick summary of what would need to be changed\updated\removed for Classic:

1. "Avoid combining Traffic Manager and Front Door" applies.  ARG query needs to be updated.
2. "Restrict traffic to your origins" applies but would have to be modified to change terminology and features available.
3. "Use the latest API version and SDK version" applies but links would need to be updated.
4. "Configure logs" applies.  Links need to be updated.
5. "Use end-to-end TLS" concept applies but ARG query and links would need to be updated.
6. "Use HTTP to HTTPS redirection" applies but ARG and doc links need to be updated.
7. "Use managed TLS certificates" applies but would need to be updated with specific FD classic links and wording.
8. "Use latest version for customer-managed certificates" applies.  Doc links need to be updated.
9. "Use the same domain name on Front Door and your origin" applies.  Wording needs to be updated.
10. "Enable the WAF" applies but ARG query would need to be rewritten.
11. "Disable health probes when there is only one origin in an origin group" applies but ARG query needs to be rewritten and wording updated.
12. "Select good health probe endpoints" applies.
13. "Use HEAD health probes" applies.
14. "Use geo-filtering" in Azure Front Door applies
15. "Secure your Origin with Private Link in Azure Front Door" does not apply.  Not supported in classic.

Lastly, a recommendation should be added to migrate from Classic to AFD Standard\Premium as it provides enhanced security features such as support for Private Link.

**Comment by ejhenry** [comment]
@Azure/aprl-networking please review

**Comment by jimays-avila** [comment]
There was a discussion about this not long ago and the discussion was around not creating recommendations for AFD classic but around adding a recommendation to the current AFD APRL recommendations stating that customers should migrate to AFD standard as soon as possible. @rodrigosantosms @ethan-hurst @judyer28

**Comment by jimays-avila** [comment]
I can get started on that.  I will work on updating the recommendation and then the ARG query.
