### ISSUE TITLE
🪲 Reports generator script not functioning. Stating it is outdated

### ISSUE THREAD

**Issue by cepomerl** [Azure/Azure-Proactive-Resiliency-Library-v2#510]
The reports generator script is giving an error stating that " This version of the script is outdated. Please use a more recent version of the script"

**Comment by tksh164** [comment]
@cepomerl - That message means the scripts that you are using are old. Could you re-download the latest scripts and use it.

To get the latest scripts:
```
iwr https://aka.ms/aprl/tools/1 -out 1_wara_collector.ps1
iwr https://aka.ms/aprl/tools/2 -out 2_wara_data_analyzer.ps1
iwr https://aka.ms/aprl/tools/3 -out 3_wara_reports_generator.ps1
```

**Comment by oZakari** [comment]
Thanks @tksh164! @cepomerl, closing this based upon @tksh164's response, but feel free to re-open if you are still running into the same issues after updating to the latest scripts.
