### ISSUE TITLE
🪲 Bug Report - VM NICs and subnets have NSGs Associated query returning extra blank results

### ISSUE THREAD

**Issue by kpoineal** [Azure/Azure-Proactive-Resiliency-Library-v2#526]
## Describe the bug

This recommendation returns the correct resources but also returns empty fields as it doesn't account for NICs that aren't attached to a VM but are still consuming IP Space in a subnet.

![Image](https://github.com/user-attachments/assets/16bd0178-7ee6-4d47-9c8f-ac643983474c)

aprlGuid                    : 82b3cf6b-9ae2-2e44-b193-10793213f676
recommendationTypeId        : 
recommendationMetadataState : Active
learnMoreLink               : {@{name=How network security groups filter network traffic; url=https://learn.microsoft.com/azure 
                              /virtual-network/network-security-group-how-it-works#intra-subnet-traffic}}
recommendationControl       : Security
longDescription             : Unless you have a specific reason, it's advised to associate a network security group to a        
                              subnet or a network interface, but not both, to avoid unexpected communication issues and
                              troubleshooting due to potential rule conflicts between the two associations.

pgVerified                  : True
description                 : VM network interfaces and associated subnets both have a Network Security Group associated        
potentialBenefits           : Reduces communication problems
tags                        : 
recommendationResourceType  : Microsoft.Compute/virtualMachines
recommendationImpact        : Low
automationAvailable         : True
query                       : // Azure Resource Graph Query
                              // Provides a list of virtual machines and associated NICs that do have an NSG associated to      
                              them and also an NSG associated to the subnet.
                              Resources
                              | where type =~ 'Microsoft.Network/networkInterfaces'
                              | where isnotnull(properties.networkSecurityGroup)
                              | mv-expand ipConfigurations = properties.ipConfigurations, nsg = properties.networkSecurityGroup 
                              | project nicId = tostring(id), subnetId = tostring(ipConfigurations.properties.subnet.id),       
                              nsgName=split(nsg.id, '/')[8]
                              | parse kind=regex subnetId with '/virtualNetworks/' virtualNetwork '/subnets/' subnet
                                  | join kind=inner (
                                      Resources
                                      | where type =~ 'Microsoft.Network/NetworkSecurityGroups' and
                              isnotnull(properties.subnets)
                                      | project name, resourceGroup, subnet=properties.subnets
                                      | mv-expand subnet
                                      | project subnetId=tostring(subnet.id)
                                  ) on subnetId
                                  | project nicId
                              | join kind=leftouter (
                                  Resources
                                  | where type =~ 'Microsoft.Compute/virtualMachines'
                                  | where isnotnull(properties.networkProfile.networkInterfaces)
                                  | mv-expand nic=properties.networkProfile.networkInterfaces
                                  | project vmName = name, vmId = id, tags, nicId = nic.id, nicName=split(nic.id, '/')[8]       
                                  | extend nicId = tostring(nicId)
                              ) on nicId
                              | project recommendationId = "82b3cf6b-9ae2-2e44-b193-10793213f676", name=vmName, id = vmId,      
                              tags, param1 = strcat("nic-name=", nicName)

## To Reproduce

Steps to reproduce the behaviour:

1. Run the query from above
2. See the empty lines.
3. Adjust query to project nicId as well, this way you can see which NICs aren't attached to VMs
4. Inspect the NICs in the portal and see that they are not attached to a VM but have a NSG attached.

## Expected behaviour

I would expect that orphaned NICs would not have their results returned.

**Comment by ejhenry** [comment]
Thanks @kpoineal, this recommendation was removed from APRL this week as part of a recommendation cleanup effort.
