### ISSUE TITLE
❓👂 Feedback - Non-accessible Learn More link

### ISSUE THREAD

**Issue by tksh164** [Azure/Azure-Proactive-Resiliency-Library-v2#528]
## Question/Feedback

Public users/customers cannot access the one of the Learn More Links of the [Ensure that each SAP production system is designed for high availability across availability zones](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-specialized-workloads/sap/#ensure-that-each-sap-production-system-is-designed-for-high-availability-across-availability-zones).

https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/52ddbc70a8d095152507aa99deb99c518302e261/azure-specialized-workloads/sap/recommendations.yaml#L17-L18

https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/52ddbc70a8d095152507aa99deb99c518302e261/azure-specialized-workloads/sap/recommendations.yaml#L40-L41

https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/52ddbc70a8d095152507aa99deb99c518302e261/azure-specialized-workloads/sap/recommendations.yaml#L65-L66

https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/52ddbc70a8d095152507aa99deb99c518302e261/azure-specialized-workloads/sap/recommendations.yaml#L108-L109

https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/52ddbc70a8d095152507aa99deb99c518302e261/azure-specialized-workloads/sap/recommendations.yaml#L142-L143

https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/52ddbc70a8d095152507aa99deb99c518302e261/azure-specialized-workloads/sap/recommendations.yaml#L195-L196

The aka.ms link redirects to **ms**.portal.azure.com, that is the reason why they cannot access it, I believe.

- **ms.portal.azure.com** (current)
    - https://ms.portal.azure.com/#blade/AppInsightsExtension/UsageNotebookBlade/ComponentId/Azure%20Monitor/ConfigurationId/community-Workbooks%2FWorkloads%2FSAP%2FInventory%20Checks%20for%20SAP/Type/workbook/WorkbookTemplateName/Inventory%20Checks%20for%20SAP

- **portal.azure.com**
    - https://portal.azure.com/#blade/AppInsightsExtension/UsageNotebookBlade/ComponentId/Azure%20Monitor/ConfigurationId/community-Workbooks%2FWorkloads%2FSAP%2FInventory%20Checks%20for%20SAP/Type/workbook/WorkbookTemplateName/Inventory%20Checks%20for%20SAP

## Possible Answers/Solutions?

We should change the target URL of https://aka.ms/ACESInventoryCheckSAP with portal.azure.com.

**Comment by ejhenry** [comment]
@shah-manish and @humblejay please review

**Comment by tksh164** [comment]
Sorry, I checked again then https://aka.ms/ACESInventoryCheckSAP works.
