### ISSUE TITLE
🪲 Bug Report - Diagnostic logs in Key Vault should be enabled - KQL query false negative

### ISSUE THREAD

**Issue by judyer28** [Azure/Azure-Proactive-Resiliency-Library-v2#53]
## Describe the bug

The KQL query for [Diagnostic logs in Key Vault should be enabled](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/KeyVault/vaults/#diagnostic-logs-in-key-vault-should-be-enabled) only checks from a policy perspective.  User could still have a Key Vault without diagnostics settings configured.    

## To Reproduce

Steps to reproduce the behaviour:

1. Create a Key Vault
2. Do not configure diagnostics logs
3. Run query.  Key Vault not captured.

## Expected behaviour

Query should report all KV without diagnostics configured.

## Screenshots 📷

If applicable, add screenshots to help explain your problem. Please feel free to blur/cover any sensitive information.

## Additional context

Anything else we should know to help us troubleshoot this bug?

**Comment by tksh164** [comment]
It is difficult to directly detect Key Vault's diagnostic settings because Azure Resource Graph does not have the capability to achieve that. I believe that Azure Resource Graph does not have tables for `Microsoft.Insights/diagnosticSettings`.

**Comment by judyer28** [comment]
Completely agree, but we also can't have a query that produces false negatives.  Users will miss recommendations if they rely on queries that do not capture all of the results.  My suggestion would be to change this to a manual check until we have a query in place that can capture all key vaults without diagnostic settings.
