### ISSUE TITLE
🪲 Bug Report - Configure DDoS Protection on the Azure Firewall VNet returns wrong result

### ISSUE THREAD

**Issue by kasimrehman** [Azure/Azure-Proactive-Resiliency-Library-v2#533]
## To Reproduce

Steps to reproduce the behaviour:

1. Create an Azure Firewall in a VNET/subnet with multiple IP addresses associated
2. Create a DDoS plan and protect the VNET created in 1.
3. Results with ddosProtection: Disabled are found.

## Expected behaviour

The VNET of the firewall is protected. It should not be found as missing DDoS protection

## Screenshots 📷

If applicable, add screenshots to help explain your problem. Please feel free to blur/cover any sensitive information.

## Additional context

properties.ipConfigurations of the Firewall is used to figure out the VNET in which the Azure Firewall is deployed. If it has several IP configurations, I observe that only the first has a property called subnet, which is used in the query below for the purpose of figuring out the VNET (as VNET id) of the Azure Firewall. The other IP configurations do not have this. Their VNET id is null. This will result in the full outer join on VNET id with the DDoS protected VNET ids returning records with null VNET id and obviously no matching DDoS plan. Maybe you need to filter out empty vNetIds like below:
```
// Azure Resource Graph Query
// List all in-scope Azure Firewall resources, where the VNet is not associated to a DDoS Protection Plan
resources
| where type =~ "Microsoft.Network/azureFirewalls"
| where isempty(properties.virtualHub.id) or isnull(properties.virtualHub.id)
| mv-expand ipConfig = properties.ipConfigurations
| project
    name,
    firewallId = id,
    tags,
    vNetName = split(ipConfig.properties.subnet.id, "/", 8)[0],
    vNetId = tolower(substring(ipConfig.properties.subnet.id, 0, indexof(ipConfig.properties.subnet.id, "/subnet")))
| where isnotempty(vNetId)
| join kind=fullouter (
    resources
    | where type =~ "Microsoft.Network/ddosProtectionPlans"
    | mv-expand vNet = properties.virtualNetworks
    | project ddosProtectionPlanId = id, vNetId = tolower(vNet.id)
    )
    on vNetId
| where isempty(ddosProtectionPlanId)
| project recommendationId = "1b2dbf4a-8a0b-5e4b-8f4e-3f758188910d", name, id = firewallId, tags, param1 = strcat("vNet: ", vNetName), param2 = "ddosProtection: Disabled"
``````

**Comment by ejhenry** [comment]
Thanks for opening this bug, @kasimrehman. The recommendation in question was removed as part of a cleanup effort as it was deemed redundant with another DDoS recommendation. I don't believe the scenario you describe would exist with the remaining DDoS recommendation, but please let us know if you still see a problem.

https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/publicIPAddresses/#public-ip-addresses-should-have-ddos-protection-enabled
