### ISSUE TITLE
💡 Feature Request - APRL Powershell to include the SAP APRL recommendations

### ISSUE THREAD

**Issue by PmeshramPM** [Azure/Azure-Proactive-Resiliency-Library-v2#68]
## Describe the solution you'd like

The request is to modify the PS script that runs the APRL where we want to list the SAP recommendations, effectively those recommendations should be listed in the excel sheet. 

## Additional context

Add any other context or screenshots about the feature request here. 📷

**Comment by shah-manish** [comment]
Also add the following:
- There are some SAP checks that override generic checks (eg in APRL v1, SAP-2 overrides VM-1)
- Can we run the PowerShell script with an additional parameter, eg workload = "SAP"? Then we can call all SAP checks.
- Add SAP recommendations from APRL to the Excel file and word document
