### ISSUE TITLE
🪲 Bug Report - This script requires specific Microsoft PowerPoint and Word templates, only available to Microsoft Cloud Solution Architects at this moment. If you are participating on a Well-Architected Reliability Assessment, reach out to the CSA coordinating the engagement.

### ISSUE THREAD

**Issue by lukemurraynz** [Azure/Azure-Proactive-Resiliency-Library-v2#85]
## Describe the bug

Unable to run: 3_wara_reports_generator.ps1, in CloudShell - as a non-Microsoft CSA (who won't have these templates) in a non-CloudShell environment either.

## To Reproduce

./3_wara_reports_generator.ps1 

## Expected behavior

PowerPoint generated

## Screenshots 📷

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/24467442/f32aed3b-7a04-4f8b-b80e-f3bab2cdd12f)

**Comment by ejhenry** [comment]
Hi @lukemurraynz - you can now find both templates in the same directory as the automation scripts. Let us know if you run into any issues with them.

**Comment by lukemurraynz** [comment]
> Hi @lukemurraynz - you can now find both templates in the same directory as the automation scripts. Let us know if you run into any issues with them.

Nice! Will have a play, appreciated.

**Comment by ejhenry** [comment]
We've also added guidance for running each of the scripts: https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/tools/script-overviews/

**Comment by lukemurraynz** [comment]
> We've also added guidance for running each of the scripts: https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/tools/script-overviews/

Magician! That saved me a blog post I was going to write!
